### ISSUE TITLE
Supporting Makefile.PL?

### ISSUE THREAD

**Issue by szabgab** [perl-actions/ci-perl-tester-helpers#10]
Do I see it correctly that the tools in this project do not support distributions that use Makefile.PL ?
If so would you be interested adding it?

**Comment by oalders** [comment]
I believe you are correct. That change would need to happen here: https://github.com/perl-actions/ci-perl-tester-helpers/blob/master/bin/build-dist

**Comment by oalders** [comment]
Closed via #15
